### ISSUE TITLE
Failed to create node.js, conf file and how to link ssr?

### ISSUE THREAD

**Issue by StarYuhen** [Asutorufa/yuhaiin#21]
### Log

read node file failed: open C:\Users\玉衡\AppData\Roaming\yuhaiin\node.json: The system cannot find the file specified.
2022/11/14 11:58:23 interfaces.go:34: open bypass file C:\Users\玉衡\AppData\Roaming\yuhaiin\yuhaiin.conf failed: open C:\Users\玉衡\AppData\Roaming\yuhaiin\yuhaiin.conf: The system cannot find the file specified., fallback to use Internal bypass data
time="2022-11-14T11:58:23+08:00" level=error msg="dns udp server listen failed: listen udp 127.0.0.1:5353: bind: An attempt was made to access a socket in a way forbidden by its access permissions."
2022/11/14 11:58:23 server.go:55: start redir failed: server redir disabled
time="2022-11-14T11:58:23+08:00" level=error msg="new tcp dns server listen at: 127.0.0.1:5353"
[log]: checked logs' file is not over 1 MB, break
2022/11/14 11:58:23 Using existing driver 0.14
2022/11/14 11:58:23 Creating adapter
2022/11/14 11:58:24 use windows proxy dll file: E:\CodeDemo\Golang\obfuscate\cmd\proxy.dll
2022/11/14 11:58:24 receive packet failed:  No more data is available.
disenabled proxy, set INTERNET_PER_CONN_FLAGS to PROXY_TYPE_DIRECT
2022/11/14 11:58:24 1 switch_system_proxy: The operation completed successfully.
2022/11/14 11:58:24 use windows proxy dll file: E:\CodeDemo\Golang\obfuscate\cmd\proxy.dll
enable proxy, set INTERNET_PER_CONN_FLAGS to PROXY_TYPE_DIRECT | PROXY_TYPE_PROXY
2022/11/14 11:58:24 1 switch_system_proxy: The operation completed successfully.
set proxy server to 127.0.0.1:8188

### issue
null conf,node.js
Don't know how to get software to link ssr

**Comment by Asutorufa** [comment]
if you don't specified host by `-host` argument, try open 127.0.0.1:50051 in browser

**Comment by Asutorufa** [comment]
node,config file will auto create.

**Comment by StarYuhen** [comment]
> node,config file will auto create.

After running the program file log prints the conf path, the file does not exist

**Comment by StarYuhen** [comment]
thanks，How the program links shadowsocks

**Comment by Asutorufa** [comment]
> thanks，How the program links shadowsocks

1. Subscribe page can add `ss://xxxx` format link or https/http subscribe link
2. Group page `Add New Node button` can generate protocol config template and add it

**Comment by Asutorufa** [comment]
> > node,config file will auto create.
> 
> After running the program file log prints the conf path, the file does not exist

Auto create when you modify config or add new node

**Comment by Asutorufa** [comment]
You can modify config in config page

**Comment by StarYuhen** [comment]
> > thanks，How the program links shadowsocks
> 
> 1. Subscribe page can add `ss://xxxx` format link or https/http subscribe link
> 2. Group page `Add New Node button` can generate protocol config template and add it

Shadowsocks related configuration content is not seen in the configuration file，Is there any relevant config file content?

**Comment by StarYuhen** [comment]
![image](https://user-images.githubusercontent.com/58671667/201640586-9368b2cb-e5c9-4f41-93ad-66373a7a3139.png)
Thank you for your answer, can you give me a configuration with ss to view

**Comment by StarYuhen** [comment]
![image](https://user-images.githubusercontent.com/58671667/201641204-31245121-3987-4c94-afc5-21186217311d.png)
The program does not create a configuration file after running, and still runs the default configuration content

**Comment by Asutorufa** [comment]
> ![image](https://user-images.githubusercontent.com/58671667/201640586-9368b2cb-e5c9-4f41-93ad-66373a7a3139.png) Thank you for your answer, can you give me a configuration with ss to view

```json
{
 "hash":  "",
 "name":  "new node",
 "group":  "template group",
 "origin":  "manual",
 "protocols":  [
  {
   "simple":  {
    "host":  "example.com",
    "port":  1080
   }
  },
  {
   "shadowsocks":  {
    "method":  "CHACHA20-IETF-POLY1305",
    "password":  "password"
   }
  }
 ]
}
```

**Comment by StarYuhen** [comment]
> > ![image](https://user-images.githubusercontent.com/58671667/201640586-9368b2cb-e5c9-4f41-93ad-66373a7a3139.png) Thank you for your answer, can you give me a configuration with ss to view
> 
> ```json
> {
>  "hash":  "",
>  "name":  "new node",
>  "group":  "template group",
>  "origin":  "manual",
>  "protocols":  [
>   {
>    "simple":  {
>     "host":  "example.com",
>     "port":  1080
>    }
>   },
>   {
>    "shadowsocks":  {
>     "method":  "CHACHA20-IETF-POLY1305",
>     "password":  "password"
>    }
>   }
>  ]
> }
> ```

Thanks, but I suggest adding templates for node and conf files in the column subfolder

**Comment by Asutorufa** [comment]
> > > ![image](https://user-images.githubusercontent.com/58671667/201640586-9368b2cb-e5c9-4f41-93ad-66373a7a3139.png) Thank you for your answer, can you give me a configuration with ss to view
> > 
> > 
> > ```json
> > {
> >  "hash":  "",
> >  "name":  "new node",
> >  "group":  "template group",
> >  "origin":  "manual",
> >  "protocols":  [
> >   {
> >    "simple":  {
> >     "host":  "example.com",
> >     "port":  1080
> >    }
> >   },
> >   {
> >    "shadowsocks":  {
> >     "method":  "CHACHA20-IETF-POLY1305",
> >     "password":  "password"
> >    }
> >   }
> >  ]
> > }
> > ```
> 
> Thanks, but I suggest adding templates for node and conf files in the column subfolder

you can generate template at web page, `group -> Add New Node`

**Comment by StarYuhen** [comment]
> > > > ![image](https://user-images.githubusercontent.com/58671667/201640586-9368b2cb-e5c9-4f41-93ad-66373a7a3139.png) Thank you for your answer, can you give me a configuration with ss to view
> > > 
> > > 
> > > ```json
> > > {
> > >  "hash":  "",
> > >  "name":  "new node",
> > >  "group":  "template group",
> > >  "origin":  "manual",
> > >  "protocols":  [
> > >   {
> > >    "simple":  {
> > >     "host":  "example.com",
> > >     "port":  1080
> > >    }
> > >   },
> > >   {
> > >    "shadowsocks":  {
> > >     "method":  "CHACHA20-IETF-POLY1305",
> > >     "password":  "password"
> > >    }
> > >   }
> > >  ]
> > > }
> > > ```
> > 
> > 
> > Thanks, but I suggest adding templates for node and conf files in the column subfolder
> 
> you can generate template at web page, `group -> Add New Node`

thank you for your help
