### ISSUE TITLE
make cli will raise error

### ISSUE THREAD

**Issue by avboy1337** [Asutorufa/yuhaiin#44]
GOOS=linux GOARCH=amd64 /usr/bin/go build -ldflags='-s -w -buildid= -X "github.com/Asutorufa/yuhaiin/internal/version.Version=v0.3.1-rc.4" -X "github.com/Asutorufa/yuhaiin/internal/version.GitCommit=c646e6a" -X "github.com/Asutorufa/yuhaiin/internal/version.BuildArch=Linux 4d4979f98fa4 5.15.0-57-generic #63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux" -X "github.com/Asutorufa/yuhaiin/internal/version.BuildTime=Mon Jan  9 20:58:54 CST 2023"' -gcflags='-m' -trimpath -o yh -v ./cmd/cli/...
github.com/Asutorufa/yuhaiin/cmd/cli
# github.com/Asutorufa/yuhaiin/cmd/cli
runtime.main_main·f: function main is undeclared in the main package
make: *** [makefile:62: cli] Error 2

**Comment by Asutorufa** [comment]
cli is deprecated, use web page instead.
