### ISSUE TITLE
shadowsocksr-libev好久没更新了

### ISSUE THREAD

**Issue by frustreated** [Asutorufa/yuhaiin#5]
如题，老哥考虑用go语言的对接不？

**Comment by Asutorufa** [comment]
不好意思, 目前没这个计划, 我个人能力有限, 目前也没时间去研究那个东西, 主要快毕业了, 事情很多, 我也是借助写这个东西学习一些东西, 前期代码写的很难看, 问题也很多, 一直在学习.

**Comment by Asutorufa** [comment]
Added, use [mzz2017/shadowsocksR](https://github.com/mzz2017/shadowsocksR)
