### ISSUE TITLE
如图所示

### ISSUE THREAD

**Issue by avboy1337** [Asutorufa/yuhaiin#7]
![image](https://user-images.githubusercontent.com/5463104/111251130-98400880-8649-11eb-99ef-e7b445ee4e38.png)

**Comment by Asutorufa** [comment]
看看同目录下有没有`yuhaiin_kernel.exe`吧, 我好久没用windows了, 如果你有时间的话可以自己编译下, 我已经了改了很多东西了.  
主要这个前端用的go 的绑定的qt, 编译很麻烦, 而且作者好像没在更新了, 以后我会换, 现在没什么时间, 在忙实习和毕业设计, 现在也就偶尔改改后端.  
而且windows下有不少能用吧, clash,qv2ray什么的, 感觉比我这个好多了.

**Comment by Asutorufa** [comment]
https://github.com/Asutorufa/yuhaiin/releases/download/v0.2.11.5-beta/windows.zip 这个是我自己编译 亲自试过可用的 再不行就没办法了
